// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_MxzTQM9BdrjQtFmOJj2BVR3TZoFd_FQ',
    appId: '1:773049980213:web:3be4f85f1e33593ffea87c',
    messagingSenderId: '773049980213',
    projectId: 'dfsdfsdf-13fd1',
    authDomain: 'dfsdfsdf-13fd1.firebaseapp.com',
    storageBucket: 'dfsdfsdf-13fd1.appspot.com',
    measurementId: 'G-V8DGQTWT0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyEeWCNCVYp8rZl1DuDNiHTxjJnvCe-oA',
    appId: '1:773049980213:android:ebc0d7adfbbaa783fea87c',
    messagingSenderId: '773049980213',
    projectId: 'dfsdfsdf-13fd1',
    storageBucket: 'dfsdfsdf-13fd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjJKQ3wHTepbgJBfGQOtkySUG34Ejd-4',
    appId: '1:773049980213:ios:a5d75b6dfed5edc6fea87c',
    messagingSenderId: '773049980213',
    projectId: 'dfsdfsdf-13fd1',
    storageBucket: 'dfsdfsdf-13fd1.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjJKQ3wHTepbgJBfGQOtkySUG34Ejd-4',
    appId: '1:773049980213:ios:a5d75b6dfed5edc6fea87c',
    messagingSenderId: '773049980213',
    projectId: 'dfsdfsdf-13fd1',
    storageBucket: 'dfsdfsdf-13fd1.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_MxzTQM9BdrjQtFmOJj2BVR3TZoFd_FQ',
    appId: '1:773049980213:web:2042ac491c49ac5bfea87c',
    messagingSenderId: '773049980213',
    projectId: 'dfsdfsdf-13fd1',
    authDomain: 'dfsdfsdf-13fd1.firebaseapp.com',
    storageBucket: 'dfsdfsdf-13fd1.appspot.com',
    measurementId: 'G-NF4QBY73X9',
  );

}